---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: {{ include "cluster.name" . }}
spec:
  apiServerLoadBalancer:
    enabled: {{ .Values.openstack.enableApiLb }}
  externalNetwork:
    id: {{ .Values.openstack.externalNetId }}
  identityRef:
    cloudName: {{ .Values.openstack.cloudName }}
    name: {{ .Values.clusterIdentity.name }}
  {{- if .Values.openstack.privateNetId }}
  network:
    id: {{ .Values.openstack.privateNetId }}
  {{- end }}
  {{- if .Values.openstack.routerId }}
  router:
    id: {{ .Values.openstack.routerId }}
  {{- end }}
  {{- if .Values.openstack.createSecurityGroups }}
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Created by cluster-api-provider-openstack - BGP (calico)
      direction: ingress
      etherType: IPv4
      name: BGP (Calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Created by cluster-api-provider-openstack - k0s controller join API
      direction: ingress
      etherType: IPv4
      name: k0s join API
      portRangeMax: 9443
      portRangeMin: 9443
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
  {{- end }}
  {{- if .Values.openstack.createNetworkInfra }}
  managedSubnets:
  - cidr: 10.6.0.0/24
    dnsNameservers:
    {{- range .Values.openstack.nameservers }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- with .Values.bastion.enabled }}
  bastion:
    {{- toYaml . | nindent 4 }}
  {{- end }}
