---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "osmachinetemplate.controlplane.name" . }}
spec:
  template:
    spec:
      flavor: {{ .Values.controlPlane.flavor }}
      image:
        filter:
          name: {{ .Values.controlPlane.image }}
      sshKeyName: {{ .Values.sshKeyName }}

